<a href="https://colab.research.google.com/github/MaineCalabrezi13/InteligenciaArtificial/blob/main/KNN_peixes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as no

In [3]:
dataframe = pd.read_csv('Fish.csv')

In [4]:
dataframe.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [6]:
pd.unique(dataframe['Species'])

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [7]:
#Informações sobre as variaveis
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Species  159 non-null    object
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB

In [8]:
#Informações estatisticas
dataframe.describe()

            Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [9]:
#Verificando especies dos peixes
pd.unique(dataframe['Species'])

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [10]:
#Verificando a quantidade de entidades por especies
dataframe['Species'].value_counts

<bound method IndexOpsMixin.value_counts of 0      Bream
1      Bream
2      Bream
3      Bream
4      Bream
       ...
154    Smelt
155    Smelt
156    Smelt
157    Smelt
158    Smelt
Name: Species, Length: 159, dtype: object>

In [11]:
#Ordinal encoder
from sklearn.preprocessing import OrdinalEncoder

In [12]:
ordinal = OrdinalEncoder()

In [13]:
species_cat = dataframe['Species']

In [14]:
#Transformando as especies (dado categorico) em numeros
species_num = ordinal.fit_transform(species_cat.values.reshape(-1, 1))

In [15]:
#Variavel que armazena as categorias
ordinal.categories_[0]

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [16]:
#Criando um dic com as categocias e seus respectivos valores
encoding_dict = dict(zip((ordinal.categories_[0]), range (len(ordinal.categories_[0]))))

In [17]:
encoding_dict

{'Bream': 0,
 'Parkki': 1,
 'Perch': 2,
 'Pike': 3,
 'Roach': 4,
 'Smelt': 5,
 'Whitefish': 6}

In [18]:
#Substituindo os valores categorico pelos dados convertidos
dataframe['Species'] = species_num

In [19]:
dataframe

     Species  Weight  Length1  Length2  Length3   Height   Width
0        0.0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0.0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0.0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0.0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0.0   430.0     26.5     29.0     34.0  12.4440  5.1340
..       ...     ...      ...      ...      ...      ...     ...
154      5.0    12.2     11.5     12.2     13.4   2.0904  1.3936
155      5.0    13.4     11.7     12.4     13.5   2.4300  1.2690
156      5.0    12.2     12.1     13.0     13.8   2.2770  1.2558
157      5.0    19.7     13.2     14.3     15.2   2.8728  2.0672
158      5.0    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [20]:
#Pegando as variaveis independentes x (tudo menos o target -> Species)
x = dataframe.drop(['Species'], axis=1)

In [21]:
x

     Weight  Length1  Length2  Length3   Height   Width
0     242.0     23.2     25.4     30.0  11.5200  4.0200
1     290.0     24.0     26.3     31.2  12.4800  4.3056
2     340.0     23.9     26.5     31.1  12.3778  4.6961
3     363.0     26.3     29.0     33.5  12.7300  4.4555
4     430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...      ...      ...      ...      ...     ...
154    12.2     11.5     12.2     13.4   2.0904  1.3936
155    13.4     11.7     12.4     13.5   2.4300  1.2690
156    12.2     12.1     13.0     13.8   2.2770  1.2558
157    19.7     13.2     14.3     15.2   2.8728  2.0672
158    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 6 columns]

In [22]:
y = dataframe['Species']

In [23]:
y

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
154    5.0
155    5.0
156    5.0
157    5.0
158    5.0
Name: Species, Length: 159, dtype: float64

In [25]:
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30, random_state=42)

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
#Modelo de Regressao
model_knn = KNeighborsClassifier(n_neighbors=3)

In [30]:
#Treinando o modelo
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [31]:
y_predict = model_knn.predict(X_test)

In [32]:
y_predict

array([2., 5., 1., 1., 2., 2., 5., 1., 2., 2., 0., 2., 0., 4., 2., 2., 2.,
       1., 0., 2., 5., 0., 0., 0., 0., 2., 4., 1., 5., 5., 0., 1., 1., 0.,
       0., 1., 4., 1., 2., 2., 0., 0., 5., 2., 4., 1., 4., 0.])

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
accuracy_score(y_test, y_predict)

0.4791666666666667

In [35]:
list_result = list()
for n_knn in range(1,100,2):
  model_knn = KNeighborsClassifier(n_neighbors=n_knn)
  model_knn.fit(X_train, y_train)
  y_predict = model_knn.predict(X_test)
  acc = accuracy_score(y_test, y_predict)
  list_result.append([acc, n_knn])

In [36]:
#Criando um dataframe dos resultados
dataframe_result = pd.DataFrame(list_result, columns=['Acurácia','N-Vizinhos'])

In [37]:
dataframe_result

    Acurácia  N-Vizinhos
0   0.479167           1
1   0.479167           3
2   0.583333           5
3   0.604167           7
4   0.604167           9
5   0.562500          11
6   0.520833          13
7   0.562500          15
8   0.541667          17
9   0.520833          19
10  0.500000          21
11  0.520833          23
12  0.437500          25
13  0.437500          27
14  0.500000          29
15  0.500000          31
16  0.500000          33
17  0.500000          35
18  0.500000          37
19  0.520833          39
20  0.500000          41
21  0.479167          43
22  0.479167          45
23  0.479167          47
24  0.479167          49
25  0.479167          51
26  0.479167          53
27  0.479167          55
28  0.479167          57
29  0.479167          59
30  0.375000          61
31  0.354167          63
32  0.291667          65
33  0.291667          67
34  0.291667          69
35  0.291667          71
36  0.291667          73
37  0.291667          75
38  0.291667          77
39  0.291667          79
40  0.291667          81
41  0.291667          83
42  0.291667          85
43  0.291667          87
44  0.291667          89
45  0.291667          91
46  0.291667          93
47  0.291667          95
48  0.291667          97
49  0.291667          99